import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { NextAuthProvider } from "./providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
    title: "Boilerplate nextScape",
    description: "Generated by kenny",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {



    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Toaster />
                    <NextAuthProvider>{children}</NextAuthProvider>

                </ThemeProvider>
            </body>
        </html>
    );
}
